title: ScaRLib Report
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ScaRLib-report.github.io

aux_links:
  Template Repository: https://github.com/davidedomini/ScaRLib-report
