title: ScaRLib Report
description: A starter template for a Jeykll site using the Just the Docs theme!
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
url: https://ScaRLib-report.github.io
search_enabled: true
